# Generated by Django 4.1.7 on 2023-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('field_of_study', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
